#!/usr/bin/env python3
"""
Mantle RWA Distribution Tracker — automation agent.

Three jobs in one run:
  1. DIGEST  — weekly markdown research brief (reports/YYYY-MM-DD.md)
  2. ALERTS  — webhook ping when a falsifiable threshold is crossed
  3. SYNC    — cross-check Dune query results vs live Routescan API (optional)

Stdlib only. Run: python3 tracker_agent.py [--alerts-only]
Env: ALERT_WEBHOOK_URL (Discord/Slack webhook, optional), DUNE_API_KEY (optional)
"""
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).parent
UA = {"User-Agent": "mantle-rwa-tracker/1.0", "Content-Type": "application/json"}


def get(url, headers=None):
    try:
        req = urllib.request.Request(url, headers={**UA, **(headers or {})})
        with urllib.request.urlopen(req, timeout=20) as r:
            return json.loads(r.read().decode())
    except Exception as e:
        print(f"[warn] fetch failed {url}: {e}", file=sys.stderr)
        return None


def post(url, payload):
    try:
        req = urllib.request.Request(
            url, data=json.dumps(payload).encode(), headers=UA, method="POST"
        )
        urllib.request.urlopen(req, timeout=20)
        return True
    except Exception as e:
        print(f"[warn] webhook failed: {e}", file=sys.stderr)
        return False


def token_snapshot(cfg, address, issuer):
    """Live snapshot from Routescan: top-1 %, issuer %, sampled holders."""
    d = get(
        f"https://api.routescan.io/v2/network/mainnet/evm/{cfg['chain_id']}"
        f"/erc20/{address}/holders?limit=100"
    )
    if not d or not d.get("items"):
        return None
    items = d["items"]
    top1 = max(float(i.get("percentage", 0)) for i in items) * 100
    issuer_pct = next(
        (float(i["percentage"]) * 100 for i in items
         if i.get("address", "").lower() == issuer.lower()),
        None,
    )
    return {
        "sampled_holders": len(items),
        "top1_pct": round(top1, 3),
        "issuer_pct": round(issuer_pct, 3) if issuer_pct is not None else None,
        "external_float_pct": round(100 - top1, 3),
    }


def mantle_tvl():
    chains = get("https://api.llama.fi/v2/chains") or []
    return next((c.get("tvl") for c in chains if c.get("chainId") == 5000), None)


def dune_check(cfg, live):
    """Compare Dune query result vs live API; return list of divergence notes."""
    key = os.environ.get("DUNE_API_KEY")
    dune = cfg.get("dune", {})
    if not (dune.get("enabled") and key):
        return []
    notes = []
    qid = dune["query_ids"].get("concentration")
    if not qid:
        return []
    d = get(
        f"https://api.dune.com/api/v1/query/{qid}/results?limit=1",
        headers={"X-Dune-API-Key": key},
    )
    try:
        row = d["result"]["rows"][0]
        dune_top1 = float(row["top1_pct"])
        for sym, snap in live.items():
            if snap and abs(dune_top1 - snap["top1_pct"]) > dune["max_divergence_pts"]:
                notes.append(
                    f"⚠️ Dune vs API divergence for {sym}: Dune {dune_top1:.2f}% "
                    f"vs live {snap['top1_pct']:.2f}% — refresh the Dune query."
                )
    except (TypeError, KeyError, IndexError):
        notes.append("⚠️ Could not read Dune results — check query ID / API key.")
    return notes


def build_alerts(cfg, sym, prev, cur):
    t = cfg["thresholds"]
    alerts = []
    if not cur:
        return alerts
    if cur["top1_pct"] < t["top1_pct_target"]:
        alerts.append(f"🚨 {sym}: top wallet below {t['top1_pct_target']}% "
                      f"({cur['top1_pct']}%) — distribution threshold CROSSED.")
    if prev:
        drop = prev["top1_pct"] - cur["top1_pct"]
        if drop >= t["alert_on_top1_drop_pts"]:
            alerts.append(f"📉 {sym}: top wallet -{drop:.2f} pts since last run "
                          f"({prev['top1_pct']}% → {cur['top1_pct']}%).")
        jump = cur["sampled_holders"] - prev["sampled_holders"]
        if jump >= t["alert_on_holder_jump"]:
            alerts.append(f"📈 {sym}: +{jump} holders in sample since last run.")
    return alerts


def digest_md(cfg, live, tvl, prev_state, alerts, sync_notes):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L = [f"# Mantle RWA Distribution Digest — {now}",
         "", "*Auto-generated by tracker_agent.py — not financial advice.*", ""]
    if tvl:
        L += [f"**Mantle DeFi TVL:** ${tvl:,.0f} (DeFiLlama)", ""]
    L += ["| Token | Top-1 wallet | External float | Sampled holders | Δ top-1 vs last run |",
          "|---|---|---|---|---|"]
    for sym, snap in live.items():
        if not snap:
            L.append(f"| {sym} | data unavailable | — | — | — |")
            continue
        prev = prev_state.get(sym)
        delta = (f"{prev['top1_pct'] - snap['top1_pct']:+.2f} pts"
                 if prev else "first run")
        L.append(f"| {sym} | {snap['top1_pct']}% | {snap['external_float_pct']}% "
                 f"| {snap['sampled_holders']} | {delta} |")
    L += ["", "## Thresholds (falsifiable)", ""]
    t = cfg["thresholds"]
    for sym, snap in live.items():
        if snap:
            check = "✅" if snap["top1_pct"] < t["top1_pct_target"] else "⬜"
            L.append(f"- {check} {sym}: top wallet < {t['top1_pct_target']}% "
                     f"(now {snap['top1_pct']}%)")
    if alerts:
        L += ["", "## Alerts", ""] + [f"- {a}" for a in alerts]
    if sync_notes:
        L += ["", "## Dune sync check", ""] + [f"- {n}" for n in sync_notes]
    L += ["", "## Sources", "",
          "- Routescan v2 API (Mantle, chainId 5000), DeFiLlama /v2/chains",
          f"- Generated {now}"]
    return "\n".join(L)


def main():
    alerts_only = "--alerts-only" in sys.argv
    cfg = json.loads((HERE / "config.json").read_text())
    state_path = HERE / cfg["state_file"]
    prev_state = json.loads(state_path.read_text()) if state_path.exists() else {}

    live, all_alerts = {}, []
    for sym, tok in cfg["tokens"].items():
        snap = token_snapshot(cfg, tok["address"], tok["issuer_wallet"])
        live[sym] = snap
        all_alerts += build_alerts(cfg, sym, prev_state.get(sym), snap)

    sync_notes = dune_check(cfg, live)
    webhook = os.environ.get(cfg["webhook_env_var"])
    if webhook and (all_alerts or sync_notes):
        post(webhook, {"content": "\n".join(all_alerts + sync_notes)})

    if not alerts_only:
        tvl = mantle_tvl()
        report = digest_md(cfg, live, tvl, prev_state, all_alerts, sync_notes)
        rdir = HERE / cfg["reports_dir"]
        rdir.mkdir(exist_ok=True)
        out = rdir / f"{datetime.now(timezone.utc):%Y-%m-%d}.md"
        out.write_text(report)
        print(f"digest written: {out}")

    # persist state for next-run deltas
    state_path.write_text(json.dumps(
        {k: v for k, v in live.items() if v}, indent=2))
    print("alerts:", len(all_alerts), "| sync notes:", len(sync_notes))


if __name__ == "__main__":
    main()
